

GET http://localhost:5001/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwZXRlckBoZC5uZXQubnoiLCJqdGkiOiI5OTUyZWQ4MS1jOTAwLTQ2OTQtOGIwNS1kMTM1ZjU0MTAyNWIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjNiNTI2YzM4LWJjODUtNDI3Ny05NzJiLWVjNzk1ZGE0Y2JiNSIsImV4cCI6MTU5MTg2NTkzMiwiaXNzIjoiWW91ckF3ZXNvbWVDb21wYW55IiwiYXVkIjoiWW91ckF3ZXNvbWVDb21wYW55In0.dHE8-IE3FilVG1saijk8x7MndK64He_48_0_PUONox0
